Add package that allows intellisense to list suggestions for driver
hpi-schul-cloud/integration-tests pull request #163
Opened 2020-09-02 15:33 UTC by Ojself

A package that allows driver to show suggestions with intellisense (only tested with vs code).

You can now do this:
<img width="521" alt="Skjermbilde 2020-09-02 kl  17 30 40" src="https://user-images.githubusercontent.com/32653149/92004360-6e289800-ed42-11ea-88ad-94879635155d.png">

2020-09-03 06:02 UTC, kgorner requested changes

2020-09-03 08:09 UTC, Ojself commented on package-lock.json
> -      "dev": true
I didn't touch this directly. I think `npm install` might have tampered with this value. I'll reset it.

2020-09-21 19:37 UTC, kgorner approved these changes
fine with me

2020-09-22 06:42 UTC, Grzesiek80 approved these changes

2020-09-22 07:02 UTC, merged

2020-09-22 08:58 UTC, Ojself commented
This branch was merged and then reversed because the package was dependent on Python