Feature/sc 5172 edita topic
hpi-schul-cloud/integration-tests pull request #207
Opened 2020-10-19 12:11 UTC by IzaSad

https://ticketsystem.hpi-schul-cloud.org/browse/SC-5172

2020-10-20 13:44 UTC, Grzesiek80 approved these changes

2020-10-22 10:06 UTC, d3n153 submitted a review, later dismissed
Fine from my side.

2020-10-22 12:35 UTC, pauljanns requested changes
One minor change has to be made, afterwards feel free to merge.

2020-10-22 12:35 UTC, pauljanns commented on page-objects/pages/coursePages/CRSSAddEditTopicPage.js
> +	let listOfTopicElements = await driver.$$(topicSelector);
I suggest using an elementHelmpers method here. E.g. getListOfAllElements()

2020-10-22 13:00 UTC, d3n153 reviewed
Found one little thing, which I can also remove with my PR if it's not needed.

2020-10-22 13:00 UTC, d3n153 commented on step_definitions/topic-steps.js
> +	// await addEditTopicPage.(changedTopicName, changedContentTitle, changedDescription);
Can this be removed, when it's not used?

2020-10-22 13:09 UTC, pauljanns approved these changes

2020-10-22 13:16 UTC, d3n153 submitted a review, later dismissed

2020-10-23 07:13 UTC, pauljanns approved these changes

2020-10-23 10:36 UTC, Grzesiek80 approved these changes

2020-10-23 12:03 UTC, merged